"""
MPPSC StudyIQ YouTube Video Summarizer Agent
Extracts video details from the channel and creates detailed study notes
"""
import asyncio
import os
import json
from datetime import datetime
from dotenv import load_dotenv
from browser_use import Agent, BrowserSession
from browser_use.llm.openai.chat import ChatOpenAI

load_dotenv()

# Output directory for notes
NOTES_DIR = "mppsc_notes"
os.makedirs(NOTES_DIR, exist_ok=True)

async def summarize_youtube_videos():
    """
    Browse MPPSC StudyIQ YouTube channel and create detailed study notes
    """
    print("\n" + "="*80)
    print("📚 MPPSC StudyIQ Video Summarizer Agent")
    print("="*80)
    print("\n🎯 Purpose: Create detailed notes from MPPSC preparation videos")
    print("📺 Channel: https://www.youtube.com/@MPPSCStudyIQ/videos")
    print("\n" + "="*80)
    
    async with async_playwright() as playwright:
        llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)
        browser_session = BrowserSession(user_data_dir=None)
        
        # Task to browse and extract video information
        task = """
You are a study notes creator for MPPSC exam preparation.

TASK:
1. Go to https://www.youtube.com/@MPPSCStudyIQ/videos
2. Look at the latest 5-10 video titles and thumbnails
3. For each video you see:
   - Note the video title
   - Note the topic category (GS Paper 1/2/3/4, Current Affairs, etc.)
   - Identify if it's about MP GK, Polity, History, Geography, Economy, etc.
   - Note the upload date
   
4. Create a summary report including:
   - List of recent videos with topics
   - Key subjects covered
   - Recommended videos for each GS paper
   
5. If any video title mentions specific topics like Constitution, MP History, 
   Current Affairs, note those specifically as they are important for revision.

OUTPUT FORMAT:
Provide a structured summary like:
---
MPPSC StudyIQ Channel Summary
Date: [Today's Date]

Recent Videos:
1. [Title] - [Topic Category] - [Date]
2. [Title] - [Topic Category] - [Date]
...

Key Topics Covered:
- GS Paper I: [topics]
- GS Paper II: [topics]
- GS Paper III: [topics]
- Current Affairs: [topics]

Recommended for Revision:
- [High priority videos based on exam importance]
---

Work efficiently and provide comprehensive output.
"""
        
        agent = Agent(
            task=task,
            llm=llm,
            browser_session=browser_session,
            use_vision=False,
            max_failures=3,
        )
        
        print("🤖 Agent starting...")
        print("📺 Browsing MPPSC StudyIQ channel...\n")
        
        try:
            result = await agent.run()
            
            # Save the summary
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{NOTES_DIR}/mppsc_studyiq_summary_{timestamp}.md"
            
            summary_content = f"""# MPPSC StudyIQ Channel Video Summary
Generated: {datetime.now().strftime("%d %B %Y, %H:%M")}

## Channel: [MPPSC StudyIQ](https://www.youtube.com/@MPPSCStudyIQ/videos)

---

## Agent Output:

{result.final_result if hasattr(result, 'final_result') else str(result)}

---

## How to Use These Notes:

### For GS Paper I (History, Art & Culture, Geography)
- Focus on videos about MP History and Indian Heritage
- Watch Geography lectures for map-based questions

### For GS Paper II (Polity & Governance)
- Constitutional provisions lectures
- MP governance and administration videos

### For GS Paper III (Economy, Environment, Science)
- Economic development videos
- Environment and ecology topics

### For Current Affairs
- Daily/Weekly current affairs compilations
- Monthly magazines discussion

---

## Revision Priority:
1. ⭐⭐⭐ Current Affairs (Last 6 months)
2. ⭐⭐⭐ MP Specific GK
3. ⭐⭐ Constitution and Polity
4. ⭐⭐ History and Culture
5. ⭐ Science and Technology

---

*Generated by MPPSC StudyIQ Summarizer Agent*
"""
            
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(summary_content)
            
            print("\n" + "="*80)
            print("✅ SUMMARY CREATED SUCCESSFULLY!")
            print("="*80)
            print(f"\n📄 Notes saved to: {filename}")
            print("\n📋 Quick Preview:")
            print("-"*40)
            if hasattr(result, 'final_result'):
                print(result.final_result[:500] + "..." if len(str(result.final_result)) > 500 else result.final_result)
            print("-"*40)
            
        except Exception as e:
            print(f"\n⚠️ Error: {str(e)}")
            print("💡 Try running again or check internet connection")
        
        input("\nPress Enter to close browser...")

if __name__ == "__main__":
    from playwright.async_api import async_playwright
    asyncio.run(summarize_youtube_videos())
